name: Build
on: 
  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Report versions
      run: |
        rustup --version
        rustc -Vv

    - name: Update rustup
      run: rustup self update

    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL `curl -s https://api.github.com/repos/rust-lang/mdBook/releases/latest | grep 'x86_64-unknown-linux-gnu.tar.gz"' | cut -d : -f 2,3 | tr -d '"' | grep 'releases/download'` | tar -xz --directory=bin
        echo "$(pwd)/bin" >> ${GITHUB_PATH}

    - name: Install mdbook-epub
      run: |
        cargo install mdbook-epub

    - name: Report versions
      run: |
        rustup --version
        rustc -Vv
        mdbook --version
        mdbook-epub --version
        which mdbook
        which mdbook-epub

    - uses: actions/checkout@v3
      with:
        repository: 'rust-lang-cn/book-cn'
        path: 'book'

    - name: modify book.toml
      run: |
        echo >> book/book.toml
        echo "[output.epub]" >> book/book.toml

    - name: build
      run: |
        cd book
        mdbook build

    - name: artifact
      uses: actions/upload-artifact@v3
      with:
        name: trpl.epub
        path: book/book/epub/*.epub
        if-no-files-found: error
        retention-days: 1